# Generated by Django 5.2.8 on 2026-07-27 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0005_centros_y_fk_solicitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador/a'), ('SUPERVISOR_DAS', 'Supervisor/a DAS'), ('SUPERVISOR_CENTRO', 'Supervisor/a de centro'), ('SOME', 'SOME'), ('FULL', 'Full'), ('SELECTOR', 'Selector'), ('COMUNICADOR', 'Comunicador')], max_length=20)),
                ('anexo_telefono', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para revocar el acceso sin borrar el historial.')),
                ('centro', models.ForeignKey(help_text='Centro base. Para ADMIN y SUPERVISOR_DAS es informativo: ven todos.', on_delete=django.db.models.deletion.RESTRICT, related_name='perfiles', to='solicitudes.centro')),
                ('centro_satelite', models.ForeignKey(blank=True, help_text='CECOSF u otro centro asociado que este funcionario tambien gestiona.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_satelite', to='solicitudes.centro')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_gestion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfiles de usuario',
                'db_table': 'gestion_perfil_usuario',
                'ordering': ['usuario__email'],
            },
        ),
    ]
