# Generated by Django 5.2.8 on 2026-07-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_centros_y_fk_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='nombre',
            field=models.CharField(default='', max_length=150),
        ),
    ]
